global:
  timezone: Asia/Kolkata
  checkers_path: /checkers/
  default_score: 1000
  env_path: /checkers/bin/
  flag_lifetime: 5
  game_hardness: 500.0
  inflation: true
  round_time: 60
  start_time: 2020-04-25 21:00:00
  game_mode: classic

flower:
  username: flower
  password: flower

storages:
  db:
    dbname: gameserver
    host: postgres
    password: gameserver
    port: 5432
    user: gameserver

  redis:
    db: 0
    host: redis
    port: 6379
    password: redis

  rabbitmq:
    host: rabbitmq
    port: 5672
    vhost: forcad
    user: rabbitmq
    password: rabbitmq
  
tasks:
  - name: hftSecretSause
    checker: hftsecretsause/checker.py
    checker_timeout: 15
    checker_type: nfr
    gets: 1
    places: 1
    puts: 1

  - name: darkPool
    checker: darkpool/checker.py
    checker_timeout: 15
    checker_type: nfr
    gets: 1
    places: 1
    puts: 1

  - name: valueInvestor
    checker: valueinvestor/checker.py
    checker_timeout: 10
    checker_type: nfr
    gets: 1
    places: 1
    puts: 1

  - name: biexStonker
    checker: biexstonker/checker.py
    checker_timeout: 10
    checker_type: nfr
    gets: 1
    places: 1
    puts: 1

  - name: recession20
    checker: recession20/checker.py
    checker_timeout: 10
    checker_type: nfr
    gets: 1
    places: 1
    puts: 1

  - name: imf
    checker: imf/checker.py
    checker_timeout: 15
    checker_type: nfr
    gets: 1
    places: 3
    puts: 1

  - name: goldman
    checker: goldman/checker.py
    checker_timeout: 15
    checker_type: nfr
    gets: 1
    places: 1
    puts: 1


teams:
  - ip: 172.19.10.11
    name: "Team1"

  - ip: 172.19.10.12
    name: "Team2"

  - ip: 172.19.10.13
    name: "Team3"